"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.glContextSet = exports.onFrameUpdate = exports.HTMLElementSource = exports.CameraSource = exports.FaceTracker = exports.BarcodeFinder = exports.InstantWorldTracker = exports.ImageTracker = exports.SequenceSource = exports.LogLevel = exports.setLogLevel = exports.browserIncompatibleUI = exports.browserIncompatible = exports.permissionRequestUI = exports.permissionDeniedUI = exports.permissionRequest = exports.permissionGranted = exports.permissionDenied = exports.Pipeline = exports.FaceLandmarkName = exports.FaceLandmark = exports.FaceMesh = exports.TargetImagePreviewMesh = exports.CameraEnvironmentMap = exports.ImageTrackerLoader = exports.HeadMaskMeshLoader = exports.FaceMeshLoader = exports.FaceMeshGeometry = exports.ImageAnchorTransformNode = exports.InstantWorldAnchorTransformNode = exports.FaceAnchorTransformNode = exports.FaceTrackerTransformNode = exports.FaceTrackerLoader = exports.CameraMirrorMode = exports.CameraPoseMode = exports.Camera = exports.skipVersionLog = void 0;
/* eslint-disable import/prefer-default-export */
/* eslint-disable import/no-unresolved */
/* eslint-disable import/extensions */
var version_1 = require("./version");
Object.defineProperty(exports, "skipVersionLog", { enumerable: true, get: function () { return version_1.default; } });
var camera_1 = require("./camera");
Object.defineProperty(exports, "Camera", { enumerable: true, get: function () { return camera_1.default; } });
Object.defineProperty(exports, "CameraPoseMode", { enumerable: true, get: function () { return camera_1.CameraPoseMode; } });
Object.defineProperty(exports, "CameraMirrorMode", { enumerable: true, get: function () { return camera_1.CameraMirrorMode; } });
var faceTracker_1 = require("./loaders/faceTracker");
Object.defineProperty(exports, "FaceTrackerLoader", { enumerable: true, get: function () { return faceTracker_1.default; } });
var faceAnchor_1 = require("./trackers/faceAnchor");
Object.defineProperty(exports, "FaceTrackerTransformNode", { enumerable: true, get: function () { return faceAnchor_1.default; } });
var faceLandmark_1 = require("./trackers/faceLandmark");
Object.defineProperty(exports, "FaceAnchorTransformNode", { enumerable: true, get: function () { return faceLandmark_1.default; } });
var instantWorldAnchor_1 = require("./trackers/instantWorldAnchor");
Object.defineProperty(exports, "InstantWorldAnchorTransformNode", { enumerable: true, get: function () { return instantWorldAnchor_1.default; } });
var imageAnchor_1 = require("./trackers/imageAnchor");
Object.defineProperty(exports, "ImageAnchorTransformNode", { enumerable: true, get: function () { return imageAnchor_1.default; } });
var face_1 = require("./mesh/face");
Object.defineProperty(exports, "FaceMeshGeometry", { enumerable: true, get: function () { return face_1.default; } });
var faceMesh_1 = require("./loaders/faceMesh");
Object.defineProperty(exports, "FaceMeshLoader", { enumerable: true, get: function () { return faceMesh_1.default; } });
var headMaskMesh_1 = require("./loaders/headMaskMesh");
Object.defineProperty(exports, "HeadMaskMeshLoader", { enumerable: true, get: function () { return headMaskMesh_1.default; } });
var imageTracker_1 = require("./loaders/imageTracker");
Object.defineProperty(exports, "ImageTrackerLoader", { enumerable: true, get: function () { return imageTracker_1.default; } });
var cameraEnvironmentTexture_1 = require("./cameraEnvironmentTexture");
Object.defineProperty(exports, "CameraEnvironmentMap", { enumerable: true, get: function () { return cameraEnvironmentTexture_1.default; } });
var target_image_preview_mesh_1 = require("./mesh/target-image-preview-mesh");
Object.defineProperty(exports, "TargetImagePreviewMesh", { enumerable: true, get: function () { return target_image_preview_mesh_1.default; } });
var zappar_1 = require("@zappar/zappar");
Object.defineProperty(exports, "FaceMesh", { enumerable: true, get: function () { return zappar_1.FaceMesh; } });
Object.defineProperty(exports, "FaceLandmark", { enumerable: true, get: function () { return zappar_1.FaceLandmark; } });
Object.defineProperty(exports, "FaceLandmarkName", { enumerable: true, get: function () { return zappar_1.FaceLandmarkName; } });
Object.defineProperty(exports, "Pipeline", { enumerable: true, get: function () { return zappar_1.Pipeline; } });
Object.defineProperty(exports, "permissionDenied", { enumerable: true, get: function () { return zappar_1.permissionDenied; } });
Object.defineProperty(exports, "permissionGranted", { enumerable: true, get: function () { return zappar_1.permissionGranted; } });
Object.defineProperty(exports, "permissionRequest", { enumerable: true, get: function () { return zappar_1.permissionRequest; } });
Object.defineProperty(exports, "permissionDeniedUI", { enumerable: true, get: function () { return zappar_1.permissionDeniedUI; } });
Object.defineProperty(exports, "permissionRequestUI", { enumerable: true, get: function () { return zappar_1.permissionRequestUI; } });
Object.defineProperty(exports, "browserIncompatible", { enumerable: true, get: function () { return zappar_1.browserIncompatible; } });
Object.defineProperty(exports, "browserIncompatibleUI", { enumerable: true, get: function () { return zappar_1.browserIncompatibleUI; } });
Object.defineProperty(exports, "setLogLevel", { enumerable: true, get: function () { return zappar_1.setLogLevel; } });
Object.defineProperty(exports, "LogLevel", { enumerable: true, get: function () { return zappar_1.LogLevel; } });
Object.defineProperty(exports, "SequenceSource", { enumerable: true, get: function () { return zappar_1.SequenceSource; } });
var defaultpipeline_1 = require("./defaultpipeline");
Object.defineProperty(exports, "ImageTracker", { enumerable: true, get: function () { return defaultpipeline_1.ImageTracker; } });
Object.defineProperty(exports, "InstantWorldTracker", { enumerable: true, get: function () { return defaultpipeline_1.InstantWorldTracker; } });
Object.defineProperty(exports, "BarcodeFinder", { enumerable: true, get: function () { return defaultpipeline_1.BarcodeFinder; } });
Object.defineProperty(exports, "FaceTracker", { enumerable: true, get: function () { return defaultpipeline_1.FaceTracker; } });
Object.defineProperty(exports, "CameraSource", { enumerable: true, get: function () { return defaultpipeline_1.CameraSource; } });
Object.defineProperty(exports, "HTMLElementSource", { enumerable: true, get: function () { return defaultpipeline_1.HTMLElementSource; } });
Object.defineProperty(exports, "onFrameUpdate", { enumerable: true, get: function () { return defaultpipeline_1.onFrameUpdate; } });
Object.defineProperty(exports, "glContextSet", { enumerable: true, get: function () { return defaultpipeline_1.glContextSet; } });
